In [1]:
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)

In [2]:
import pandas as pd

In [4]:
review_data = pd.read_csv('/K8 Reviews v0.2.csv').drop('sentiment',axis=1)
review_data.head()

                                              review
0             Good but need updates and improvements
1  Worst mobile i have bought ever, Battery is dr...
2  when I will get my 10% cash back.... its alrea...
3                                               Good
4  The worst phone everThey have changed the last...

In [5]:
review_data.shape

(14675, 1)

In [6]:
review_data.isnull().sum()

review    0
dtype: int64

In [7]:
review_data['clean_review'] = review_data['review'].apply(lambda x: str(x).lower())
review_data.head()

,review,clean_review
0,Good but need updates and improvements,good but need updates and improvements
1,"Worst mobile i have bought ever, Battery is dr...","worst mobile i have bought ever, battery is dr..."
2,when I will get my 10% cash back.... its alrea...,when i will get my 10% cash back.... its alrea...
3,Good,good
4,The worst phone everThey have changed the last...,the worst phone everthey have changed the last...

In [8]:
review_data['clean_review'] = review_data['clean_review'].str.replace(r'[^a-zA-Z\s]', ' ',regex=True)
review_data.head()

,review,clean_review
0,Good but need updates and improvements,good but need updates and improvements
1,"Worst mobile i have bought ever, Battery is dr...",worst mobile i have bought ever battery is dr...
2,when I will get my 10% cash back.... its alrea...,when i will get my cash back its alrea...
3,Good,good
4,The worst phone everThey have changed the last...,the worst phone everthey have changed the last...

In [9]:
review_data['clean_review'] = review_data['clean_review'].str.replace(r'\s{2,}', ' ',regex=True)
review_data.head()

,review,clean_review
0,Good but need updates and improvements,good but need updates and improvements
1,"Worst mobile i have bought ever, Battery is dr...",worst mobile i have bought ever battery is dra...
2,when I will get my 10% cash back.... its alrea...,when i will get my cash back its already january
3,Good,good
4,The worst phone everThey have changed the last...,the worst phone everthey have changed the last...

In [10]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [13]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [14]:
review_data['clean_review'] = review_data['clean_review'].apply\
(lambda x: [WordNetLemmatizer().lemmatize(word) for word in x])
review_data.head()

,review,clean_review
0,Good but need updates and improvements,"[g, o, o, d, , b, u, t, , n, e, e, d, , u, ..."
1,"Worst mobile i have bought ever, Battery is dr...","[w, o, r, s, t, , m, o, b, i, l, e, , i, , ..."
2,when I will get my 10% cash back.... its alrea...,"[w, h, e, n, , i, , w, i, l, l, , g, e, t, ..."
3,Good,"[g, o, o, d]"
4,The worst phone everThey have changed the last...,"[t, h, e, , w, o, r, s, t, , p, h, o, n, e, ..."

In [15]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

True

In [16]:
review_data = review_data[review_data['clean_review'].map(lambda x: len(x)) > 1].reset_index(drop=True)
# Keeping records with more than single words

In [17]:
review_data.head()

,review,clean_review
0,Good but need updates and improvements,"[g, o, o, d, , b, u, t, , n, e, e, d, , u, ..."
1,"Worst mobile i have bought ever, Battery is dr...","[w, o, r, s, t, , m, o, b, i, l, e, , i, , ..."
2,when I will get my 10% cash back.... its alrea...,"[w, h, e, n, , i, , w, i, l, l, , g, e, t, ..."
3,Good,"[g, o, o, d]"
4,The worst phone everThey have changed the last...,"[t, h, e, , w, o, r, s, t, , p, h, o, n, e, ..."